- AUTHORS.md
> Added Santiago Soler as author

- doc/references.rst
This will help keep them sane in the long run.
Add links to the DOIs as well.
> Put references in alphabetical order

- .appveyor.yml
- .travis.yml
- environment.yml
- setup.py
Test on CIs, switch main environment file to 3.7 and add setup.py
metadata tag
> Add tests for Python 3.7

- data/examples/earth_geoid.py
- data/examples/earth_gravity.py
- data/examples/earth_topography.py
- examples/gravity_disturbance.py
- examples/normal_gravity.py
Use the same orthometric projection and make larger figures for better
proportion of texts.
**Reminders**
> Some tweaks to global maps in the gallery

- .appveyor.yml
- .travis.yml
Don't clone from master to avoid breaking the builds when the scripts
update.
**Reminders**
> Pin version of CI scripts to 1.0.0

- .azure-pipelines.yml
Some builds were failing because of permission issues for conda. Adding
this seems to solve those problems.
Fixes the issues in #78
**Reminders**
> Take ownership of conda on Azure Mac builds

- AUTHORS.md
Add contributors to Harmonica that where missing on the AUTHORS.md file.
**Reminders**
> Add contributors to AUTHORS.md

- MANIFEST.in
Include the new `AUTHORSHIP.md` on `MANIFEST.in` so it can be added when
packaging Harmonica.
**Reminders**
> Include AUTHORSHIP.md on MANIFEST.in

- CITATION.rst
- README.rst
- doc/changes.rst
- doc/citing.rst
- doc/index.rst
- doc/install.rst
Add `doc/changes.rst` file containing a changelog.
Add instructions on how to cite Harmonica to documentation.
Add Zenodo badge on `README.rst` and link to the future `v0.1.0` documentation.
Add `conda` and `pip` installing instructions in `doc/install.rst`.
**Reminders**
> Add changelog entry for v0.1.0

- .github/workflows/continuous-integration.yml
- .github/workflows/style.yml
Add a label to GitHub Actions for easily identify them on the checks list.
**Reminders**:
> Add "test" label to Actions on continuous-integration.yml

- LICENSE.txt
Inspired on fatiando/verde#296
Related to fatiando/maintenance#9
**Reminders**:
> Use only first year of publication in the copyright notice

- MANIFEST.in
> Include requirements.txt in MANIFEST.in

- doc/changes.rst
Replace `PROJECT` for `harmonica` on the links to the PRs
**Reminders**:
> Fix links to PRs on doc/changes.rst

- README.rst
- doc/changes.rst
Add link to Harmonica `v0.2.0` on `README.rst`
**Reminders**:
> Add changelog for v0.2.0

- README.rst
- doc/changes.rst
> Add changelog for v0.2.1

- env/requirements-docs.txt
- environment.yml
Updates also sphinx gallery and sphinx book theme. Fixes an issue between of
Sphinx 3.5.* trying to import a deprecated `environmentfilter` function from
latest jinja2. Update Python version to 3.9 in the `environment.yml` file.
> Update Sphinx version to 4.5.0

- AUTHORS.md
I add my info. I put my first because it says alfabetically.
> Add Federico Esteban to AUTHORS.md

- AUTHORS.md
> Add Lu Li to AUTHORS.md

- AUTHORS.md
Adding my info to the authors list.
> Add Matt Tankersley to AUTHORS.md

- AUTHORS.md
Fix small typo in Federico's affiliation.
> Fix typo in AUTHORS.md

- AUTHORS.md
Update Santiago Soler's affiliation in `AUTHORS.md`.
> Update Santi's affiliation to UBC

- README.md
- doc/changes.rst
- doc/versions.rst
Update `doc/changelog.rst` with latest changes. Add links to new version docs
in `README.md` and `doc/versions.rst`.
> Update changelog for Harmonica v0.5.0

- .github/workflows/test.yml
Update GitHub Action for Codecov to version 3.
Inspired by fatiando/pooch#345
> Update Codecov Action to v3

- doc/user_guide/transformations.rst
Add horizontal derivatives to the Grid Transformation section in the User Guide. Show how we can compute them using finite differences or fft-based derivatives.
Related to #378
> Add horizontal derivatives to the user guide

- doc/conf.py
Add ``ensaio`` to ``intersphinx_mapping`` in ``doc/conf.py``.
> Add ensaio to intersphinx mapping

- doc/changes.rst
- doc/versions.rst
Add changelog to `doc/changes.rst` and add link to documentation of v0.6.0 to `doc/versions.rst`.
> Add changelog for v0.6.0

- doc/user_guide/transformations.rst
Fix some words.
I think this might be the clearest highpass/lowpass example I have seen written anywhere!
> Minor edits to grid transformations guides

- harmonica/tests/test_tesseroid_layer.py
Fix typo in test function for tesseroid layer.
> Fix typo in test function name

- harmonica/_forward/prism_magnetic.py
Fix the first line of the docstring of `_prism_single_component`.
> Fix docstring in private function in `prism_magnetic.py`

- AUTHORS.md
> Add Yago M Castro to AUTHORS.md

- AUTHORS.md
Add India Uppal to the list of authors.
> Add India Uppal to AUTHORS.md

- .flake8
- env/requirements-style.txt
- environment.yml
- harmonica/_equivalent_sources/cartesian.py
- harmonica/_equivalent_sources/gradient_boosted.py
- harmonica/_equivalent_sources/spherical.py
- harmonica/_forward/prism_gravity.py
- harmonica/_forward/prism_layer.py
- harmonica/_forward/tesseroid_layer.py
- harmonica/_io/icgem_gdf.py
- harmonica/filters/_fft.py
- harmonica/tests/test_legendre.py
- harmonica/tests/test_tesseroid.py
Bump versions of Black, isort, Flake and plugins in `environment.yml` and in `env/requirements_style.txt`. Run black with latest version. Apply changes required by latest flake.
> Bump version of isort, black and flake8

- doc/references.rst
- doc/user_guide/equivalent_sources/block-averaged-eqs.rst
- doc/user_guide/equivalent_sources/index.rst
- examples/equivalent_sources/cartesian.py
- harmonica/_equivalent_sources/cartesian.py
- harmonica/_equivalent_sources/gradient_boosted.py
- harmonica/_equivalent_sources/spherical.py
Replace wrong citations to Cordell (1992) in equivalent sources docs and examples.
Fixes #508
> Fix wrong citations of Cordell (1992)

- AUTHORS.md
Add Gelson Ferreira de Souza Junior to the AUTHORS.md
> Add Gelson to AUTHORS.md

- doc/changes.rst
- doc/versions.rst
Add v0.7.0 to the list of previous documentation pages.
> Create changelog for v0.7.0

- Makefile
Fix wrong variable name in `Makefile`.
> Fix variable name in Makefile
