fatiando/harmonica

harmonica/io.py
harmonica/tests/test_icgem.py

The latitude and longitude were being read as 2D arrays and referenced
to "northing" and "easting" helper coordinates. Since this grid is not
projected, there is no need for that. 
Rename coordinates to "latitude" and "longitude" instead of "lon" "lat".
Refactor the function to be a bit smaller when creating the array.
Mainly, prepare all arguments before instantiating the Dataset instead
of assigning the values afterward.
**Reminders**

Refactor load_icgem_gdf and simplify coordinates

---

harmonica/ellipsoid.py

Add `first_eccentricity` property to `ReferenceEllipsoid`.
Fixes #26
**Reminders**

Add first_eccentricity to RefereceEllipsoid

---

doc/_static/figures/airy-isostasy.svg
doc/references.rst
examples/isostasy_airy.py
harmonica/isostasy.py
harmonica/tests/test_isostasy.py

I simplified the implementation of the Airy isostatic Moho to only handle the traditional cases: crust, mantle, and water density. Don't ignore the water by default. This can be achieved by masking the topography if desired. Also include the reference Moho depth in the arguments to output Moho depth instead of root thickness. This is the most common use case and the roots can still be calculated using 0 reference depth. The implementation now handles `xarray.DataArray` input and fills out metadata.
Extended the documentation and gallery example text and added a figure to explain the geometry of the problem.
**Reminders**

Simplify Airy code and make compatible with xarray

---

doc/api/index.rst
examples/gravity_disturbance.py
examples/gravity_disturbance_topofree.py
harmonica/__init__.py
harmonica/constants.py
harmonica/gravity_corrections.py
harmonica/tests/test_gravity_corrections.py

Adds a `bouguer_correction` function that calculate the planar Bouguer correction for land and oceans. The topography provided can be a numpy array or `xarray.DataArray`. Includes an example application to the global gravity sample data. In this case, need to convert the geoid-referenced ETOPO1 topography to ellipsoid heights. 
Fixes #8 
**Reminders**

Function for planar Bouguer correction

---

harmonica/coordinates.py

Replace the bad styling `180 / numpy.pi` for the `numpy.degrees()` function for converting
radians to degrees.
Fixes #42 
**Reminders**

Improve radians to degrees conversion

---

doc/api/index.rst
harmonica/__init__.py
harmonica/coordinates.py
harmonica/tests/test_coordinates.py

Convert geocentric spherical coordinates to geocentric coordinates (defined by the
`ReferenceEllipsoid`). Only geodetic `geocentric_latitude` and `radius` are converted to
`latitude` and `height`, geocentric and geodetic longitudes are equal.
Also add links on `spherical_to_geodetic` and `geodetic_to_spherical` to each other on
theirs docstring.
Add tests for new function: 
1. Test with a "spherical" ellipsoid (in such case the geodetic and gecentric
coordinates are the same).
2. Test with real ellipsoids on equator and poles (on those points geodetic and
geocentric latitudes are must be equal).
3. Perform an identity test, i.e. applying `geodetic_to_spherical` and then
`spherical_to_geodetic` must be equal to the identity operator, obtaining the
original set of `latitude` and `height`. …

Add geocentric to geodetic coordinates conversion

---

.pylintrc
.travis.yml
environment.yml
requirements-dev.txt

Pylint has started complaining about numpy imports. Disable these checks
and add numpy to their whitelist. Pin the pylint version so that this
type of errors doesn't creep up on new PRs and we upgrade pylint only
when we want to.
**Reminders**

Pin pylint to 2.2.2 and fix numpy-related lint

---

AUTHORS.md
LICENSE.txt
doc/conf.py
setup.py

Replaces my name with "The Harmonica Developers" in authorship claims and
copyright notices. Include a definition of what that term means in the
AUTHORS.md file.
Left my name and email as maintainer on the setup.py because we don't
have a project email yet.

Assign authorship to "The Harmonica Developers"

---

.appveyor.yml
.travis.yml
doc/install.rst
setup.py

Change support for Python 3.6 or higher because conda-forge is no longer
building 3.5 packages.
Fixes #51 
**Reminders**

Drop support for Python 3.5

---

.appveyor.yml
.azure-pipelines.yml
.travis.yml

Was using the master branch by mistake in Azure Pipelines.
**Reminders**

Fix: CI scripts 1.1.1 instead of master in Azure

---

doc/references.rst
harmonica/ellipsoid.py

Add `mean_radius` property to `ReferenceEllipsoid` class to compute the
arithmetic mean radius of the ellipsoid defined after Moritz (2000).
Moritz (2000) https://doi.org/10.1007/s001900050278
**Reminders**

Add mean radius property to ReferenceEllipsoid

---

harmonica/coordinates.py
harmonica/tests/test_coordinates.py

Geographic coordinates conversion functions now get the full coordinates
as arguments rather than only the `latitude` and `radius`/`height`, and returns
the full set of converted coordinates.
The previous implementation was inconvenient for real applications.
**Reminders**

Refactor coordinates conversion

---

harmonica/tests/test_tesseroid.py

The docstring of the script containing test functions for tesseroids was wrong.
**Reminders**

Fix wrong docstring on script of tesseroid tests

---

harmonica/tests/test_tesseroid.py
harmonica/tests/utils.py

Make function wrapper of require_numba decorator run the decorated function passed as
arguument. Refactor accuracy tests for tesseroids to solve some hidden mistakes produced
by previous untested lines.
Fixes #90
**Reminders**

Fix require_numba decorator

---

harmonica/forward/tesseroid.py

Add size of density array and number of tesseroids on the error message
when they mismatch in order to make clearer what's failing.
The improvement of such error messages was triggered after #98.
**Reminders**

Improve error message for invalid density array

---

harmonica/equivalent_layer/harmonic.py

The attributes argument for the sklearn.utils.validation.check_is_fitted
function is going to be deprecated. Remove the attributes passed to the
check_is_fitted function used on the EQLHarmonic.predict method.
Fixes #133
**Reminders**

Remove attributes argument from check_is_fitted

---

harmonica/equivalent_layer/harmonic.py

Rollback the changes in #134 because scikit-learn reverted the deprecation of
attributes in check_is_fitted. See scikit-learn/scikit-learn#15947

Revert the use of attributes in check_is_fitted 

---

.azure-pipelines.yml
.travis.yml
data/examples/README.txt
doc/api/index.rst
environment.yml
harmonica/datasets/__init__.py
harmonica/datasets/sample_data.py
harmonica/tests/test_sample_data.py
requirements.txt
setup.py

With Pooch 0.7.0, the recommended way of loading the registry file is
with `pkg_resources` (see fatiando/pooch#120). It's also better to use
the default cache location so users can more easily clean up unused
files. Because this is system specific, add the
`harmonica.datasets.locate` function to return the cache folder
location.
**Reminders**

Use pooch.os_cache and pkg_resources in datasets

---

CITATION.rst
README.rst

Replace the reserved Zenodo DOI for the first release with the global
Zenodo DOI for Harmonica. Zenodo makes available the global DOI of the
release after it's released. So, the only DOI available at the time was
the one corresponding to the first release: v0.1.0. It's better to have
the global DOI on the badge from `README.rst` and on citation
instructions on `CITATION.rst`.
**Reminders**

Replace global Zenodo DOI on badges and citation

---

.azure-pipelines.yml
.travis.yml
setup.py

Set the metadata flags on `setup.py` to include 3.8 and specify that
it's Python 3 only.
Fixes #147 
**Reminders**:

Add CI builds for Python 3.8

---

harmonica/equivalent_layer/harmonic.py

`EQLHarmonca` docstrings were wrongly pointing to itself as the drafted
"`HarmonicEQL`" class. Replace `HarmonicEQL` for `EQLHarmonic`.

Fix wrong name of EQLHarmonic class on docstrings

---

harmonica/io.py
harmonica/tests/test_icgem.py

Previously just assumed `fname` was a string and called `open` on it.
Now, check if it's a file-like object (has a `read` method) and don't
open it if that's the case. Use `contextlib` to keep the `with`
statement in case we do have to open the file. This is useful if the
file is compressed and can be opened with `bz2.open`, `gzip.open`, etc
before passing on to the function.
**Reminders**:

Allow load_icgem_gdf to take open file objects

---

harmonica/equivalent_layer/harmonic.py

Now, docstrings of Equivalent Layer classes properly describe the
Greens' function as the _inverse Euclidean distance_.
**Reminders**

Replace Cartesian distance for Euclidean distance

---

.travis.yml

Set `NUMBA_THREADING_LAYER` to `workqueue` on Travis CIs running Ubuntu.
Solution obtained from https://github.com/numba/numba/issues/5983.
**Reminders**:

Fix infinite loop on CIs after Numba v0.5.0

---

.travis.yml
environment.yml
examples/eql/harmonic_spherical.py
harmonica/equivalent_layer/harmonic.py
requirements.txt
setup.py

Overwrite `dims` and `extra_coords_names` class attributes of EQL gridders based on the coordinate system of the gridder.
Update gallery example fo spherical EQL. Avoid passing the `projection` argument when gridding the data and grid it directly into spherical coordinates.
Pin Verde to `>=1.5.0`.
Fixes #170, fixes #174.
**Reminders**:

Update EQLs after last changes on Verde BaseGridder

---

.azure-pipelines.yml
environment.yml
examples/eql/harmonic_spherical.py
harmonica/equivalent_layer/harmonic.py

After version 19, black changed the formatting slightly in a few files.
This updates the format and sets a minimum version of black in the
development environment and the CI.
**Reminders**:

Run black and require >=20.8b1

---

harmonica/tests/test_sample_data.py

After Pooch v1.1.1 the cache directory where all sample data are downloaded to
is created when a dataset is fetched and not on initialization as before. This
makes the `test_datasets_locate()` to fail on a fresh installation of Harmonica
(where no dataset has been downloaded yet). The solution proposed in Verde
(https://github.com/fatiando/verde/pull/271) is to fetch one dataset before
running the `locate()` function.
**Reminders**:

Fetch a sample data before testing locate() function

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml
.github/workflows/style.yml

Add [cancel-workflow-action](https://github.com/marketplace/actions/cancel-workflow-action) to the `test` job on `continuous_integration.py` workflow so any previous job that is still being run gets cancelled, so we focus the CIs resources on the last push.
**Reminders**:

Cancel previous runs of GitHub Actions

---

harmonica/equivalent_layer/utils.py

Parallelize the build of the Jacobian matrix and the prediction step on
equivalent layer gridders through `numba.prange` iterators. This enables the
`fit` and `predict` methods to use all the available CPUs, greatly reducing the
computational time. The `prange` is only applied to the outer loops for each
task, i.e. distributing computation points between CPUs, but leaving the
iteration through the sources on single ones.
**Reminders**:

Parallelize EQLs predictions and Jacobian build

---

.github/workflows/continuous-integration.yml
.github/workflows/deploy.yml

Update `setup-miniconda` GitHub Action to `v2.0.1` and use the one
released by `conda-incubator` instead of one of its forks.

Update setup-miniconda Action to v2.0.1

---

harmonica/equivalent_layer/utils.py
harmonica/forward/point_mass.py
harmonica/tests/test_eql_harmonic.py
harmonica/tests/test_forward_utils.py

Replace `coordiantes` for `coordinates`.
**Reminders**:

Fix typos on coordinates

---

setup.py

On `setup.py`, build the `INSTALL_REQUIRES` variable by reading the `requirements.txt` file.
**Reminders**:

Get INSTALL_REQUIRES from requirements.txt

---

Makefile
license_notice.py

Add a new `license_notice.py` script that checks if the license notice is
present on every source file or adds it to them. Source files are `.py` files
not ignored on `.gitignore`. Run the file on the `check` and `format` targets
on Makefile. Lint and style check the new `license_notice.py` file.
Related to fatiando/maintenance#12
**Reminders**:

Automatically check for license notice

---

.github/workflows/deploy.yml

For test releases to TestPyPI we have to edit the setuptools_scm
configuration to produce valid version numbers. But it turns out that
this breaks the number for actual releases. To fix it, only edit the
configuration on non-release builds.
Issue raised on https://github.com/fatiando/verde/pull/317
**Reminders**:

Fix wrong version numbers for PyPI releases

---

harmonica/equivalent_layer/harmonic.py
harmonica/equivalent_layer/harmonic_spherical.py
harmonica/equivalent_layer/utils.py
harmonica/tests/test_eql_harmonic.py

Add the option to enable/disable parallelization on EQLs through a new
`parallel` attribute that can be set on initialization or anytime.
Add dispatcher functions to choose between the regular version or the
parallized version of the `predict_numba` and `jacobian_numba` functions.
**Reminders**:

Add parallel flag to EQLs

---

harmonica/equivalent_layer/utils.py
harmonica/forward/point_mass.py
harmonica/forward/prism.py
harmonica/forward/tesseroid.py
harmonica/tests/test_point_mass.py
harmonica/tests/test_prism.py

Parallelize the outer loops of `prism_gravity` and `point_mass_gravity`. Add an
optional `parallel` argument to `prism_gravity` and `point_mass_gravity` to run
them in parallel or in serial at will. Refactor and optimize tesseroids forward
model: avoid defining a set of point masses to compute their effect, instead
compute results in runtime. Simplify its code, reduce memory consumption and
prevent tesseroid forward model from using `jit_point_mass_spherical` function
which has been parallelized, but we don't want to use its parallel version when
computing GLQ on tesseroids forward model.
Fixes #204 
**Reminders**:

Optimize forward models

---

.github/workflows/test.yml
setup.py

Add Python 3.9 to the CI tests.
Related to fatiando/maintenance#14
**Reminders**:

Extend support for Python 3.9

---

doc/api/index.rst
examples/forward/prism_layer.py
examples/forward/prisms_topo_gravity.py
harmonica/__init__.py
harmonica/forward/prism_layer.py
harmonica/tests/test_prism_layer.py

Also rename the xarray accessor class to `DatasetAccessorPrismLayer`
**Reminders**:

Rename prisms_layer for prism_layer

---

environment.yml
requirements-dev.txt

Unpin `sphinx` from `environment.yml` and `requirements-dev.txt`.
Solve the toctree issue where the p tags were not getting a `caption`
class.
**Reminders**:

Unpin Sphinx

---

harmonica/forward/prism_layer.py

Change the order of the dimensions of `DataArrays` in the examples of
`prism_layer`, since `xarray v0.19.0` prints them in a different order. Tell
`pytest` to ignore the outputs of the `print` statements in the `prism_layer`
examples while running doctests.
Related to https://github.com/fatiando/verde/pull/329

Change order of dims in example of prism_layer

---

examples/forward/prisms_topo_gravity.py
harmonica/forward/prism_layer.py
harmonica/tests/test_prism_layer.py

Extend the support of `prism_layer` to accept `surface`, `reference`, and
properties as `xarray.DataArray`. Improve the test functions by creating
a `pytest` fixture that parametrizes the data types of the output arrays:
either Numpy arrays or `xarray.DataArray`s. Generate a new `pytest` fixture
that returns a layer of prisms with some holes (missing prisms), ready to be
used as the expected results of some test functions. Parametrize the `field` on
each test function that computes gravitational fields of prism layers. Simplify
the `prism_layer_topo` example so the surface and the density of the layer are
passed as xarray objects.
**Reminders**:

Allow prism_layer to take xarray objects as arguments

---

harmonica/tests/utils.py

The require_numba as a function wrapper makes it hard to use
`pytest.mark.parametrize` on test functions. Following pytest
documentation, it's better to define custom decorators as global
variables.
Source: https://docs.pytest.org/en/6.2.x/skipping.html#id1

Transform require_numba decorator into a global variable

---

harmonica/equivalent_sources/cartesian.py

Fix typo en `EquivalentSources` docstring: replace `bloc_size` for `block_size`.
**Reminders**:

Fix typo on EquivalentSources docstring

---

.github/workflows/style.yml
harmonica/version.py

Create a new step in `style.yml` Action for checking if the license notice is
present in every single source file.
**Reminders**:

Make Actions to check license notice in source files

---

harmonica/equivalent_sources/cartesian.py
harmonica/equivalent_sources/utils.py
harmonica/tests/test_eq_sources_cartesian.py
harmonica/tests/test_eq_sources_utils.py

The `dtype` argument is used to cast the inputs of the `fit` method, to build
the location of the point sources, to allocate the Jacobian matrix and
therefore to produce predictions. Add a new utility function for casting the
inputs of the fit method to the desired `dtype`. Add new test file for the
equivalent sources utility functions. Add tests for the new feature. Simplify
test suite for equivalent sources through fixtures.
**Reminders**:

Add dtype argument to EquivalentSources

---

harmonica/tests/test_gradient_boosted_eqs.py

Replace the old `point_mass_gravity` for the `point_gravity` function in
gradient-boosted equivalent sources tests. The old function name was still
there because of the simultaneous development of the new feature with the
renaming of the function.
**Reminders**:

Use prism_gravity on gradient-boosted tests

---

.github/workflows/test.yml
doc/install.rst
setup.cfg

Remove the compatibility metadata, remove from the CI matrix, bump the
`python_requires` to 3.7+.
**Relevant issues/PRs**
Inspired on https://github.com/fatiando/verde/pull/364 and triggered by CI errors in #238

Drop support for Python 3.6

---

harmonica/__init__.py
harmonica/forward/point.py
harmonica/tests/test_point_gravity.py

Remove point_mass_gravity function from harmonica because it was deprecated on
PR #280. Remove related test functions.
Fix #308

Remove deprecated point_mass_gravity function

---

examples/equivalent_sources/block_averaged_sources.py
examples/equivalent_sources/cartesian.py
examples/equivalent_sources/gradient_boosted.py
examples/equivalent_sources/spherical.py
harmonica/equivalent_sources/cartesian.py
harmonica/equivalent_sources/spherical.py
harmonica/tests/test_eq_sources_cartesian.py
harmonica/tests/test_eq_sources_spherical.py
harmonica/tests/test_gradient_boosted_eqs.py

The `grid()` method of Verde gridders now take a `coordinates` argument with
the coordinates of the target grid. The previous `region`, `shape` and
`spacing` arguments will be deprecated in Verde v2.0.0. This change makes it
easier for our equivalent sources classes: we don't need the extra `upward`
argument, users can create the coordinates of the target grid using
`verde.grid_coordinates` and pass them via `coordinates` argument. Ditch the
`upward`, `shape`, `spacing` and `region` arguments from the equivalent sources
gridders. Replace them for the new `coordinates` argument: users need to
provide the coordinates of the target grid instead of building it through the
grid method. Raise errors if any of those old arguments are being passed. Raise
warnings if any kwargs are …

Ditch soon-to-be deprecated args of equivalent sources grid method

---

doc/user_guide/equivalent_sources/index.rst
doc/user_guide/topographic_correction.rst

Fix link to EquivalentSources.predict method and fix superscripts in the docs.

Fix small format errors in the user guide

---

doc/user_guide/forward_modelling/point.rst

Add "spherical" when describing the spherical latitude coordinate of point
masses in the user guide. This way we differentiate it from the "latitude"
geodetic coordinate.
I just add 'spherical' following the description of the coordinate system where 'latitude' is used for geodetic (NOT spherical) coordinates.
Is this correct? Now I have some doubts.

Specify "spherical latitude" when describing coordinates of point masses

---

doc/user_guide/coordinate_systems.rst

Add sentence in "important".
"They would be the same if the reference ellipsoid were a sphere. "

Note that spherical and geodetic latitudes are equal in spherical ellipsoids

---

harmonica/forward/tesseroid.py

Remove expected results for tesseroid calculations in docstring examples.
Printing floats in forward modelling examples isn't that meaningful and often
creates failures when running doctests: small differences between the expected
and the got value could occur under some dependency and OS combinations.

Avoid checking floats in tesseroid doctests

---

harmonica/forward/prism.py
harmonica/tests/test_prism.py

Discard null prisms before passing them to the forward modelling
functions. A null prism is the one that has either zero volume or zero
density. Since they don't contribute to the generated field, we can save
some computation time by discarding them.
Related to #65 (@aguspesce noticed some zero division errors when passing zero volume tesseroids to the forward model computation).

Discard prisms with no volume or zero density

---

doc/changes.rst

Hey, Harmonica curious user here! 
I found out that some links in the [change.rst](https://github.com/fatiando/harmonica/blob/main/doc/changes.rst) return a 404 error. 
I manually replaced all the `<https://github.com/fatiando/PROJECT/pull/*>` by  `<https://github.com/fatiando/harmonica/pull/*>`. 
Is it the way to do or is there any automatic implementation behind it? anyway, I let you review the PR according to your standards ;)
Thanks for your awesome work!

Replace PROJECT placeholder in changes.rst for "harmonica"

---

examples/equivalent_sources/block_averaged_sources.py
examples/equivalent_sources/cartesian.py
examples/equivalent_sources/gradient_boosted.py

Hi Fatiando team!
First I'm happy to see that the upward continuation is now live in v0.5.0. I was using it until now with the old Fatiando!
This PR is related to a documentation issue and specifically to the example in the [equivalent source page](https://www.fatiando.org/harmonica/latest/gallery/equivalent_sources/gradient_boosted.html#sphx-glr-gallery-equivalent-sources-gradient-boosted-py)
**Issue**: the plot of the upward continued data is empty.
**Small tweak**: add the `region = vd.get_region(coordinates)` line to the examples. This allows getting the right coordinates to grid.
Looking forward to using the upward continuation feature!

Fix equivalent sources figures in gallery examples

---

harmonica/forward/_tesseroid_utils.py
harmonica/forward/tesseroid.py
harmonica/tests/test_tesseroid.py

When I am working on `tesseroid_layer` function, I had an error for tesseroid with zero volume. 
So I add a new checked in `tesseroid_gravity` that ignore the tesseroid with zero density or zero volume

Add a function to ignore the tesseroid with zero density or volume

---

harmonica/tests/test_icgem.py

The test for checking if proper errors and warnings were raised when reading an empty ICGEM gdf file was failing in my local system due to a change in the Numpy warning for the empty file. Took the opportunity to refactor the test using `pytest.raises` and `pytest.warns` to capture the errors and warnings.

Fix test function for empty ICGEM gdf file

---

README.md
doc/changes.rst
doc/versions.rst

Add links to new versions in README.md and doc/versions.rst.

Add changelog for v0.5.1

---

harmonica/forward/prism.py

In the prism forward modelling we need to evaluate the kernel functions on each
of the vertices of the prism by passing shifted coordinates, i.e. the
coordinates of the vertices from a coordinate system located in the observation
points. Now we avoid recomputing shifted coordinates by moving their definition
to outer for loops.

Minor optimization in prism forward modelling

---

doc/api/index.rst

Add the new `tesseroid_layer` function to the API reference along with the
`DatasetAccesorTesseroidLayer` class.
Related to #316

Add tesseroid_layer to the API reference

---

environment.yml

Update `environment.yml` so `flake8-unused-arguments` gets installed
from conda-forge rather than from PyPI.

Install flake8-unused-arguments from conda-forge

---

harmonica/forward/prism_layer.py

Found some typos in the docstrings.

Fix typos in docstrings of `prism_layer.py`

---

.github/workflows/docs.yml
env/requirements-docs.txt

Configure the `setup-miniconda` GitHub action with `use-only-tar-bz2: false`, allowing mamba to use files other than `.tar.bz2`. Otherwise mamba cannot install latest versions of some packages that aren't provided as those files. Pin Ensaio to greater than v0.5. This version of Ensaio couldn't be installed before this change.

Disable tar.bz2 only in setup-miniconda Action

---

harmonica/tests/test_eq_sources_cartesian.py
harmonica/tests/test_eq_sources_spherical.py
harmonica/tests/test_gradient_boosted_eqs.py

Instead of using the marked-as-deprecated `verde.datasets.CheckerBoard` class, use the new `verde.synthetic.CheckerBoard` on gallery and user guide examples.

Use Verde's CheckerBoard class from synthetic module

---

.github/workflows/docs.yml
.github/workflows/pypi.yml

The `publish` job now requires that the `build` job should be finished before starting. This solves the issue of the `publish` job not finding the uploaded artifact. Update the versions of the `upload-artifacts` and `download-artifacts` to v3 in `pypi.yml`.

Make "publish" job in Actions to need the "build" as finished

---

doc/user_guide/equivalent_sources/eqs-parameters-estimation.rst

Fixed a small typo I noticed in the docs. Just missed `v.0.6.0` :unamused:

minor typo in eq sources parameter estimation docs

---

harmonica/_forward/prism_layer.py

Removing the unused horizontal coordinates when discarding thin prisms of a prism layer. Since we only check the vertical boundaries, we can exclude the horizontal ones.

Remove horizontal coordinates when ditching thin prisms

---

.github/workflows/docs.yml
env/requirements-docs.txt

Fixes issue with GitHub Actions not being able to build the documentation due to missing `python3` kernel. Explicitly installing `ipykernel` solves the problem.
Problem first encountered in #393

Add ipykernel as requiement for building the docs

---

harmonica/_forward/prism_layer.py
harmonica/tests/test_prism_layer.py

Add an optional `drop_null_prisms` flag to the prism layer `to_pyvista()` method that ditches the prisms that have zero volume or `nan` values in their top or bottom boundaries. These null prisms won't be included in the PyVista Unstructured grid. By default the flag is set to `True`. Add a new test for this new feature.
Fixes #392

Drop null prisms when converting a prism layer to pyvista

---

doc/user_guide/coordinate_systems.rst
doc/user_guide/equivalent_sources/block-averaged-eqs.rst
doc/user_guide/equivalent_sources/eq-sources-spherical.rst
doc/user_guide/equivalent_sources/eqs-parameters-estimation.rst
doc/user_guide/equivalent_sources/gradient-boosted-eqs.rst
doc/user_guide/equivalent_sources/index.rst
doc/user_guide/forward_modelling/point.rst
doc/user_guide/forward_modelling/prism.rst
doc/user_guide/forward_modelling/tesseroid.rst
doc/user_guide/gravity_disturbance.rst
doc/user_guide/topographic_correction.rst
doc/user_guide/transformations.rst
env/requirements-docs.txt
environment.yml

Add download links to every User Guide page so they can be downloaded as Python scripts or Jupyter notebooks. Bump version of jupyter-sphinx to v0.4 so we can make use of the download roles.

Download User Guides as scripts and notebooks

---

harmonica/tests/test_prism_layer.py

Since the latest PyVista update, the `UnstructuredGrid.cell` attribute is a generator, and therefore it cannot be indexed. This broke our tests, that were indexing cells in the `UnstructuredGrid` for prism layers to compare them with the boundaries of each prism in the layer.

Fix prism_layer test when accessing PyVista cells

---

.github/workflows/test.yml

Let the CI job fail if the codecov upload fails. Otherwise it could stop and we wouldn't know.
Inspired by https://github.com/fatiando/verde/pull/409

Fail CI if codecov upload fails

---

harmonica/_forward/point.py
harmonica/_forward/prism.py
harmonica/_forward/prism_layer.py
harmonica/_forward/tesseroid.py
harmonica/_forward/tesseroid_layer.py

Improve the description of coordinates in several forward modelling functions (prisms, tesseroids and points). Fix wrong dimension of the `coordinates` as an array, and improve writing style. Fix wrong order of coordinates in `tesseroid_layer`.

Improve coordinates description in forward functions

---

doc/changes.rst

Use double backticks when mentioning deprecated equivalent sources classes in `changes.rst`.

Fix style for class names in changes.rst

---

env/requirements-docs.txt
environment.yml

Try to fix docs not building due to Pyvista complaining about lacking of `trame`.

Fix docs not building: install trame

---

doc/api/index.rst

Fix issue that wasn't generating the links to the `prism_layer` and `tesseroid_layer` functions in the API Reference.

Fix prism and tesseroid layer in API Reference

---

harmonica/tests/test_visualizations.py

Replace the deprecated `pv_grid.cell_bounds()` for an iterator over the cells (`pv_grid.cell`) and then use `Cell.bounds` to get the bounds of each cell.
Fixes tests failing in #422 reported by @LL-Geo

Fix visualization test using deprecated PyVista method

---

harmonica/_forward/tesseroid.py
harmonica/tests/test_tesseroid_variable_density.py

Explicitly set `nopython=True` on jit function in tests and examples.
This avoids some warnings about the change of the default configuration
in Numba: by default `nopython` will be set to `True` in the future.

Specify nopython=True on jit functions

---

pyproject.toml

When using the "file" field type, PyPI putting the entire contents of the file into the license field and mislabeling it as MIT. Replace it with just the string for the license name and not the contents of the file.

Use a text field for license in pyproject.toml

---

doc/install.rst

Updated how to pip install the development version.  The previous version caused `error: subprocess-exited-with-error`. I have updated based on the suggestion in the error message which is also similar to the Verde documentation.

Update how to pip install dev version in install.rst

---

harmonica/tests/test_icgem.py

The test was looking for a `UserWarning` with specific text that was changed in numpy. Fix it by making a much less specific regex and that will be compatible with both versions. Also fix a `FutureWarning` about accessing `xarray.Dataset` dimension sizes (should use `.sizes` instead of `.dims`).

Fix broken ICGEM file loader test

---

.github/dependabot.yml
.github/workflows/docs.yml
.github/workflows/pypi.yml
.github/workflows/test.yml

The Actions we use have pinned versions and it's almost impossible to keep up with new releases of them. Add configuration for Dependabot to track the Actions versions and send pull requests when new versions are available. This only works if version numbers are pinned instead of the commit hashes. I think the benefit of being updated out weight any risk associated with this.

Use Dependabot to update GitHub Actions workflows

---

.github/workflows/docs.yml
.github/workflows/pypi.yml

The v3 one fails to download artifacts from upload-artifact v4.

Bump actions/download-artifact to v4

---

doc/user_guide/transformations.rst

Fix spelling of "Gaussian" in tranformations guide

---

pyproject.toml

Reduce the number of urls in `pyproject.toml` by removing the ones that were redundant. Keep only links to `Documentation`, `Changelog`, `Bug Tracker`, and `Source Code`.
Related to https://github.com/fatiando/choclo/pull/77

Remove redundant urls in pyproject.toml

---

doc/user_guide/equivalent_sources/block-averaged-eqs.rst
doc/user_guide/equivalent_sources/eq-sources-spherical.rst
doc/user_guide/equivalent_sources/gradient-boosted-eqs.rst
doc/user_guide/equivalent_sources/index.rst
doc/user_guide/topographic_correction.rst
examples/equivalent_sources/block_averaged_sources.py
examples/equivalent_sources/cartesian.py
examples/equivalent_sources/gradient_boosted.py
examples/equivalent_sources/spherical.py
examples/forward/point_gravity.py

The `color` argument in plot functions of PyGMT has been removed, so we need to replace it for the new `fill` argument.
Fixes #449

Replace `color` for `fill` in examples using PyGMT

---

doc/user_guide/forward_modelling/prism.rst
examples/forward/prism_layer.py
harmonica/tests/test_prism_layer.py

Fix typos when mentioning the `DatasetAccessorPrismLayer` class in docstrings and tests.

Fix multiple typos on `DatasetAccessorPrismLayer`

---

.github/workflows/test.yml

Fix an if statement that checks if the current runner is a Ubuntu machine. Instead of comparing the `matrix.os` variable, rely on the `$RUNNER_OS` env variable provided by Actions. Add echo commands to increase verbosity.
Changes motivated by the modifications introduced in #499

Fix check of runner OS in test Action

---

.coveragerc

Replace the old `_version_generated.py` for the new `_version`.py in the configuration of `coverage`.

Add _version.py to .coveragerc

---

.github/workflows/test.yml
AUTHORS.md

Remove the push to codecov step from the `test` job into a new job that depends on the test job. Upload the coverage reports as artifacts after testing, and reuse the artifacts in the new job. Upload all coverage reports in a single push to Codecov to minimize the number of hits.
Related to fatiando/community#151

Move codecov push to its own job in Actions workflow

---

AUTHORS.md
harmonica/_equivalent_sources/gradient_boosted.py
harmonica/tests/test_gradient_boosted_eqs.py

Change the default value for the `window_size` in the `EquivalentSourcesGB` constructor to `"default"`: window size will be estimated to locate approximately 5000 data points in each window. If `window_size="default"` and less than 5000 data points are used to fit the sources, a single window for all data and sources will be used. Check if the passed value of `window_size` is valid. Add a new `window_size_` attribute to the class that is set after fitting the sources. Update docstrings and extend tests.
Fixes #425

Change default for window size in EquivalentSourcesGB

---

harmonica/_equivalent_sources/cartesian.py
harmonica/_equivalent_sources/gradient_boosted.py
harmonica/_forward/prism_layer.py

Convert Numpy scalars to Python numbers so the outputs of examples that are being compared when running doctests support Numpy>=2.0. Cast `points` in equivalent source classes to the desired `dtype` passed as argument.

Extend support for Numpy 2.0

---

harmonica/_equivalent_sources/gradient_boosted.py
harmonica/tests/test_gradient_boosted_eqs.py

Change the default value for the `depth` argument in `EquivalentSourcesGB` to `"default"`. Set the depth argument in the same way as `EquivalentSources` does, relying on the inherited methods. Extend docstrings to reflect these changes.
Fixes #513

Change default value for depth in EquivalentSourcesGB

---

harmonica/tests/test_legendre.py

Apply decorators to tests for the associated functions to compute the Legendre polynomials so we lower the time it takes to run the tests: mark the ones that test the Schmidt identity (running with high degrees) to require Numba JIT to be enabled, mark the other ones as `use_numba` so they are run with and without Numba JIT. Add low degree versions of the tests using the Schmidt identity to also check coverage with those.

Decorate tests for Legendre functions

---

harmonica/_equivalent_sources/cartesian.py
harmonica/tests/test_eq_sources_cartesian.py
harmonica/tests/test_gradient_boosted_eqs.py

Raise error message for zero depth values in EquivalentSources and EquivalentSourcesGB classes.
Add associated tests.
Fix #523

Raise error for zero depth value in equivalent sources

---

.github/workflows/docs.yml
environment.yml

The `build` package in `conda-forge` is outdated, `python-build` should be used instead.

Replace `build` for `python-build` in environment.yml

---

README.md

We mentioned in the README that horizontal derivatives would go into Verde but we ended up coding them here. So remove that from the README and include normal interpolation instead,

Remove mention of not doing horizontal derivatives

---

README.md

The badges in the README had hyperlinks in the whitespace between them because of the line breaks in the `<a>` tags. Make them all a single line to remove the links.

Remove links from whitespaces between README badges

---

.github/workflows/docs.yml

Fix a broken installation of Miniforge while running the workflow to build the docs. Update the configuration to use Miniforge and `conda` instead of Mambaforge and `mamba`, respectively.

Fix broken Miniforge installation in `docs.yml`

---

harmonica/tests/test_eq_sources_cartesian.py
harmonica/tests/test_eq_sources_spherical.py
harmonica/tests/test_gradient_boosted_eqs.py

Test cartesian equivalent sources with f32 and f64 dtypes and also with `damping` as `None` and with a very small value. Mark the combination of `damping=None` and `dtype=np.float32` with `xfail`, so it gets flagged but `pytest` doesn't error out. Since the equivalent sources with damping are more accurate, we don't need to have different absolute tolerances for both cases: keep a single value for `atol`. Set some very low absolute tolerances in spherical equivalent sources tests and in gradient-boosted equivalent sources tests.
Fixes #546

Fix equivalent sources tests failing after sklearn 1.6.0

---

.github/workflows/actions.yml
.github/workflows/docs.yml
Makefile
env/requirements-style.txt
environment.yml
harmonica/filters/_filters.py

Make use of `zizmor` to lint GitHub Actions workflows and catch potential security issues. Add `zizmor` to the `environment.yml` and to the `requirements-style.txt`. Add a new `check-actions` target in the `Makefile` that runs `zizmor` on every workflow. Add a new workflow for running `zizmor` on PRs and on pushes to `main`. 
Todo:
Part of [fatiando/community#159](https://github.com/fatiando/community/issues/159)

Use zizmor to lint GitHub Actions

---

.github/workflows/docs.yml

Set the `ENSAIO_DATA_FROM_GITHUB=true` environment variable in the docs build so data are fetched from GitHub instead of Zenodo. Helps reduce the amount of times we hit Zenodo for data downloads.

Fetch Ensaio data from GitHub in CI

---

.github/workflows/docs.yml
.github/workflows/pypi.yml
.github/workflows/test.yml

For security, it's better to pin versions of third-party Actions to commit hashes. This is because the tags used for versions can be changed to point to a different (possibly malicious) commit while the hash can't. Dependabot can still update using the hashes so it's not a huge issue.

Pin third-party Actions using commit hashes

---

harmonica/_utils.py
harmonica/tests/test_utils.py

When the intensity is very small (<1e-10), the vector to angles calculation fails because of the masking that was used. It rounds these numbers to zero and returns always inc=90, dec=0. To handle this, use the arctangent instead of arcsine in the equations. This was, we can use arctan2 which is able to handle 0 in the denominator. Add tests to make sure this doesn't happen again. These small values appear in magnetic microscopy and we ran into this issue in Magali.

Fix vector to angles for small intensities

---

env/requirements-docs.txt
environment.yml

Constrain VTK to `9.4.*` in `requirements-docs.txt`.

Solve import error of VTK in GitHub Actions
